### ISSUE TITLE
Use as Intro. 

### ISSUE THREAD

**Issue by futomtom** [Dromaguirre/DRDynamicSlideShow#8]
Hi I tried to use DRDynamicSlideShow like this 
-viewdidLoad   //My MainVC
{
  UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:[NSBundle mainBundle]];
    _introView = [storyboard instantiateViewControllerWithIdentifier:@"intro"];   // @"intro" is MainViewController  in this demo code.   
    [self presentViewController:_introView animated:NO completion:nil];
}
but the result is blank Content,  how is the correct usage , when use as Intro, Thanks. 

and also I plan to dismiss intro viewcontroller  by this. 
-(void)finishIntroToMainView {
[self dismissViewControllerAnimated:true completion:nil];
}

**Comment by Dromaguirre** [comment]
Hi there.

I can't really take care of any issues right now since I'm pretty busy with high school, but I'm working on [__something new__](https://github.com/Dromaguirre/DRDynamicSlideShow/issues/9#issuecomment-81181453) that will probably solve your current problem.
